# Generated by Django 4.2.4 on 2023-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
