# Generated by Django 4.2.4 on 2023-08-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_waitlist_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='ai_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
