# Generated by Django 4.2.4 on 2023-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_waitlist_ai_request_alter_waitlist_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
