# Generated by Django 4.2.4 on 2024-03-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_waitlist_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='company_name',
            field=models.CharField(blank=True, default='NoCompanyName', max_length=100),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='first_name',
            field=models.CharField(default='NoFirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='last_name',
            field=models.CharField(default='NoLastName', max_length=50),
        ),
    ]
