# Generated by Django 4.2.4 on 2024-03-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_waitlist_company_name_waitlist_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='company_name',
        ),
    ]
